
# preload the wallpaper(s)
preload = /home/skarki/Downloads/mountain.jpg
#preload = /home/skarki/.config/wallpaper/my_wall.jpg

# assign to each monitor
wallpaper = eDP-1,/home/skarki/Downloads/mountain.jpg
